spring.application.name=painel-economico-api

awesome.api.url=https://economia.awesomeapi.com.br/json

news.api.url=https://newsapi.org/v2
news.api.key=${NEWS_API_KEY}

# Actuator
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always
management.info.app.name=Painel Economico BFF
management.info.app.version=1.0.0

# Configuração do Resilience4j
resilience4j.circuitbreaker.instances.indicators.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.indicators.minimum-number-of-calls=5
resilience4j.circuitbreaker.instances.indicators.automatic-transition-from-open-to-half-open-enabled=true
resilience4j.circuitbreaker.instances.indicators.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.indicators.sliding-window-type=COUNT_BASED
resilience4j.circuitbreaker.instances.indicators.sliding-window-size=10